// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db_generated

import (
	"time"
)

type Healthcheck struct {
	ID        interface{}
	CreatedAt time.Time
}

type Post struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Body      string
	Author    interface{}
}

type User struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}
