// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package db_generated

import (
	"context"
	"time"
)

const createPost = `-- name: CreatePost :one
insert into posts (id, created_at, title, body, user_id)
values (?, ?, ?, ?, ? )
returning id, created_at, updated_at, title, body, user_id
`

type CreatePostParams struct {
	ID        interface{}
	CreatedAt time.Time
	Title     string
	Body      string
	UserID    interface{}
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.Title,
		arg.Body,
		arg.UserID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts 
WHERE id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id interface{}) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPostById = `-- name: GetPostById :one
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.body, posts.user_id, users.email
FROM posts JOIN users ON posts.user_id = users.id
WHERE posts.id = ?
`

type GetPostByIdRow struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Body      string
	UserID    interface{}
	Email     string
}

func (q *Queries) GetPostById(ctx context.Context, id interface{}) (GetPostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i GetPostByIdRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.Email,
	)
	return i, err
}

const getPostsPage = `-- name: GetPostsPage :many
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.body, posts.user_id, users.email
FROM posts JOIN users ON posts.user_id = users.id
ORDER BY posts.created_at DESC
  LIMIT ?2 OFFSET ?1
`

type GetPostsPageParams struct {
	PagingOffset int64
	PageSize     int64
}

type GetPostsPageRow struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Body      string
	UserID    interface{}
	Email     string
}

func (q *Queries) GetPostsPage(ctx context.Context, arg GetPostsPageParams) ([]GetPostsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsPage, arg.PagingOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsPageRow
	for rows.Next() {
		var i GetPostsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Body,
			&i.UserID,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
