[server]
port = 5000
bind_address = "127.0.0.1"  # empty string means all interfaces
root=""

[site]
# use this to configure all links on the page for running on an url,
app_path = "" 

# data for site header and also SEO/opengraph
title = "Gotths App"
description = "Cool forum app"
default_image = "/img/assets/logo.jpg"
keywords = "Forum, Anonymous, Sample App"

[cache]
default_expiration = "5m"
cleanup_interval = "10m"

